### ISSUE TITLE
Magic (What shall the rules/mechanics command patterns be?)

### ISSUE THREAD

**Issue by rheadkid** [rheadkid/Quest-Group_Project#1]
I'm thinking about creating an object for each of the spells listed here (combining the ones with identical functions, of course):
http://www.ifwiki.org/index.php/Spells

---
Here's a little input from The Pixie (from the forum):

I would handle spells as objects. Move the object to the spell book when learnt, each spell can have a script attribute that does the work when cast, plus a description. You could have other attributes for when the spell is augmented or inverted. It is a lot more flexible. Have a spell type to handle the basics:

http://docs.textadventures.co.uk/quest/using_inherited_types.html

And this is what I used for Deeper:

https://github.com/ThePix/quest/wiki/CombatLib

---

### What do YOU think?

Submit an issue to provide your input.

This will be our voting system, unless/until we find something better.

**Comment by ThePix** [comment]
We could add more obvious names to spells, so "frotz" could have "light" as an alternative name; those less familar with the history might find it easier to remember.

---

In the game universe, perhaps magic comes from the earth, and so would not work in space. You could then rationalise no magic for a sci-fi zone by siting it in orbit or another planet. Perhaps it is just weird on another planet.

---

Some of those spells could require a lot of effort for _everyone_.

bekdab | Turn iron to rust. Every item anyone creates that is ironmust be able to respond to this (which may be as siple as setting a Boolean), and the zone must be completable if this is done to everything.

malyon | Bring life to inanimate objects Even worse than bekdab, as this could affect anything! And ideally everything would have its own description of what it then does. Or is this restricted to statues and the like?

tinsot | Cause liquids to freeze. Again, each liquid must be handled separately (freezing an NPCs beer vs freezing the river).

I am not saying they should not be done, but if they are done, all authors need to be aware of them, and to script objects acordingly and plan quests aroundthem (there is an inverting spell, so these things would be reversible).

The way to implement would be to give script attributes with the spell name, and when the spell is cast, check what has that attribute, and then run it. Having a "river" type and a "pint of beer" type would make that much easier.

---

I would suggest teleportation only works within the current zone. It will be best to use the enter script of the gateway to set any attributes for this realm, but that requires the player to always arrive there first.

Each zone could have a xyzzy destination, set on the player object in the enter script of the gateway.

**Comment by rheadkid** [comment]
Excellent!

The player could (sometimes) have the ability to draw magical power/reserves from force-lines in the ground, the water, the sky, and dark matter in outer space.

Each type of force-line grants you different increases/decreases of certain attributes.

E.g., the magic from the ground increases strength a little as well as granting you the ability to perform certain powerful spells. The magic you draw from the dark matter makes you weigh less (so you could jump higher and run faster? hell I don't know... brainstorm!) and makes certain spells more/less powerful.

---
Some worlds have no magic to draw from.

Some worlds SEEM to have no magic to draw from, but, come to find out, it does but an antagonist is somehow absorbing/using it all up!

---
An inverting spell is a must have.

(Maybe you can find certain objects that are magical or anti-magical as well?)

---
>bekdab | Turn iron to rust. Every item anyone creates that is iron must be able to respond to this (which may be as simple as setting a Boolean), and the zone must be completeable if this is done to everything.

>malyon | Bring life to inanimate objects Even worse than bekdab, as this could affect anything! And ideally everything would have its own description of what it then does. Or is this restricted to statues and the like?

>tinsot | Cause liquids to freeze. Again, each liquid must be handled separately (freezing an NPC's beer vs freezing the river).

Sounds equally exhausting and exciting.

I say we give it a shot and see how things turn out.

It wouldn't take much to override the ones we don't like to just issue a 'I didn't understand your command.' Right?

**Comment by DarkLizerd** [comment]
Could some spells require a component that is required to cast the spell? 
Or it could be reserved for higher level spells.
Xyzzy could be required to be cast twice, once to set a location and the second time to return to it.
Bekdab: should require a touch effect, cast the spell then the next thing touched get rusted. It could be used to "rust" a lock, but a large iron door may require a casting to rust it. Now, we would be talking about HP for objects.

**Comment by hegemonkhan** [comment]
"We could add more obvious names to spells, so "frotz" could have "light" as an alternative name; those less familar with the history might find it easier to remember. (Pixie)"

---------

ya, I had no idea what 'frotz' was... that richard was using, lol.

definately would be needed for us who've not played early TAs

**Comment by hegemonkhan** [comment]
some ideas on magic/elemental/damage types (shown together with opposing type):

fire ~ water/ice
air/wind ~ earth
light ~ dark/shadow
holy ~ unholy/vile
sun
moon
nature (plants): example: 'vine' spell to 'tangle' (slow) or hold/stop
creature (animals/critters/insects/etc): example call on wolves/bear/bees/etc to help in a battle/fight, or maybe a giant eagle to fly on for traveling (Hobbit/LotR reference, well escaping the orcs/white-orc band and traveling to a safe distance away, and close to the lone mountain/smaug, in the Hobbit movie, anyways)
life ~ death
physical ~ magical/mental
gravitational
dimensional
spacial
temporal

----------------

spell types/effects (using TES:Morrowind idea):

(what are the different things that magic/spells do?)

**Comment by hegemonkhan** [comment]
FFH2 magic system (we can at least use for our own ideas):

ht.tps://forums.civfanatics.com/attachments/spheres-jpg.148716/
ht.tps://forums.civfanatics.com/threads/ffh-2-manual.265888/ (if you don't mind, download the FFH2 manual, and you can see much of this mods content, including on magic, there's a lot of really good content/ideas, as the makers of this mod, are long time pen and paper D&D, and have a really rich game design in FFH2)

**Comment by XanMag** [comment]
Who has two thumbs and is overwhelmed by complex combat systems?

**Comment by hegemonkhan** [comment]
don't worry, we're a team, we'll help each other, and hopefully learn how to do stuff we didn't know how to do before, that's mainly why I'm here, hehe, to learn more code designs and learn how to go about making a game, as I'm still totally green, with code and especially game making.

I barely understand how to do magic myself, took me a lot of re-reading of Pixie's spell library to finally get just the opposite element/damage types, lol. I don't think I still understand too clearly on how to do the different magic effects that Pixie does, it's still a bit confusing for me, as I still have trouble with such abstract and encapsulation designs working together to make it work.

**Comment by rheadkid** [comment]
[Get the low-down from the duplicate thread](https://github.com/rheadkid/Quest-Group_Project/issues/3#issuecomment-317347617)

c-l-o-s-e-d
