### ISSUE TITLE
Duplicate initials?

### ISSUE THREAD

**Issue by rheadkid** [rheadkid/Quest-Group_Project#11]
It may be wise to keep of list of contributor's initials, just in case two of us have SAME initials!

Here're my working initials:

---
- RH  - Richard Headkid

---

**Comment by DarkLizerd** [comment]
DL
Or, maybe go for 3 or 4 letters...
LIZ I have used in the past.

**Comment by ThePix** [comment]
I will use PX.

**Comment by hegemonkhan** [comment]
HK for Hegemonkhan, NOT 'hong kong', lol

DL... my brain goes straight to 'down load', not Dark Lizard, hehe-lol

**Comment by rheadkid** [comment]
This shouldn't be posing a problem, but we can still comment to log contributors...

Closed to help clean up the Issues page.
