### ISSUE TITLE
HINTS and HELP

### ISSUE THREAD

**Issue by rheadkid** [rheadkid/Quest-Group_Project#13]
There are a couple of few choices. 

Any thoughts?

**Comment by hegemonkhan** [comment]
it is more work for us, but I think it's important to have a 'help, hint, solution' system for these type of games (quest / text adventure). for example (you'd type in as a Command input)

help: the front door is locked, you need to find a way to unlock the front door to get into the house. You can try these actions (blah actions) in this location, which might cause something to happen...

hint 1: something on the ground
hint 2: doormat

solution: pull the doormat to find a key to the front door

**Comment by hegemonkhan** [comment]
optionally, a pedia/information system can be quite helpful too, but this is a lot of work, which may not be worth it, unlike a help/hint/solution system, which is much more important (people can use it if they get stuck in the game, instead of having to try to get in contact with us or other players of the game for help)

**Comment by XanMag** [comment]
Not sure which method we want to use for a hint system, but I used one for X2 which I think worked out pretty well.  I also might consider having a link to a different website where the player can browse for the hint that they need.  If we choose the latter, we would not need to code it into the game itself, but rather share a website or other documentation that we can upload to independently and not be confined to using an internal hint system.  Does that make sense?

**Comment by rheadkid** [comment]
making a page dedicated to and linking to this

closed

comments always open though
