### ISSUE TITLE
Teleportation

### ISSUE THREAD

**Issue by rheadkid** [rheadkid/Quest-Group_Project#15]
It seems the player would be constrained to rooms within the 'region' in which they are currently playing.

**Comment by DarkLizerd** [comment]
Unless there is a reason to teleport the player from one world to another without returning to the main hub, I can't see any reason to do this.

**Comment by rheadkid** [comment]
We'd just need a response when someone tries it: 'you are not powerful enough to dimension hop such a distance.'

**Comment by hegemonkhan** [comment]
I think using 'dimensions' and 'portals' would be best for descriptiveness in game of locations and of transportation (via physically:Exits/whatever, or magically: spells, should we decide upon having it)

----------

would it be a good idea to have the main/starting hub-location or the 'purgatory' (or is this our main/starting location? I wasn't paying attention if it is or is another location), randomly selects a destination, might make the game more interesting that way, or it could not be good for our game design too, what are your thoughts on it?

**Comment by rheadkid** [comment]
It's like The Pixie **_knew_** we may run into such a obstacle!

```
if (GetBoolean(player.parent, "gateway")) {
        msg (this.travelmsg)
        player.parent = hub
      }
      else {
        msg ("You can't travel from here.")
      }
```

---
Closing this out, due to prepreparedness.

(What? If antidisestablishmentarianism isn't an oxymoron, I can use prepreparedness!)

---
That Pixie!

Prognosticator Extraordinaire!

I just needed to read...

_Singing to self:_

&#9835; Just take a look.
It's in a <del>book</del> repo!
The Reading Railroad! &#9835;

(Wait, is that right?<a style="color:blue" title="This is a joke. And apparently a bad one, since I feel the need to explain it...">*</a>)
