### ISSUE TITLE
Room descriptions

### ISSUE THREAD

**Issue by rheadkid** [rheadkid/Quest-Group_Project#17]
I don't dig using 'You are in...', I prefer the room name in bold.

I also like the location bar to be black with white text.

Will it hurt if we have different settings in each galaxy/region/gateway? (I'm going to call our individual submissions galaxies, unless someone coins a better term for them. They are but galaxies within an infinite universe.)

**Comment by DarkLizerd** [comment]
Actually... if the different worlds had different location bar color, it would keep the player aware of which world they are in and when they change worlds. But, beyond that, I think the descriptions layout should be the same, or at least similar.
IE:
**The Kitchen**
It is a 1950's era kitchen with the pale green walls and the black and white checkerboard floor is just too much. There is a close door to the north, an archway to the west, and another closed door to the south.

>

(So, should the exits be described in the room description, (the description flow would be more fluid) or should the exits be listed separately?)

**Comment by hegemonkhan** [comment]
I second it (different settings/look/formatting/colors/etc), as it would add to the uniqueness of each world/location and/or time-period.

maybe a better word: dimensions, hehe :D

as a 'dimension' can be a different place (spacial) and/or time (temporal) and/or "as an alternate reality/time-event flow: you woke up on the left side of the bed instead of the right side, and now hitler rules the world instead of being defeated in ww2"... stuff like that, and 'dimensions' can be created/added and destroyed/removed without much explanation (well if removed/destroyed, we'd have an explantion of it), as people understand the open concept of 'dimensions', and also the use of 'portals' (traveling) goes with 'dimensions'.

**Comment by rheadkid** [comment]
>(So, should the exits be described in the room description, (the description flow would be more fluid) or should the exits be listed separately?

I vote full story-teller mode all the way. Exits, object descriptions... (I'll probably get lazy and turn the object descriptions back on, but I don't know. The way the default descriptions print sort of detracts from reading. (The hyperlinks even more so. (And don't get me started on the side-panes! (Not that I don't click rather than type when the option exists...))))

Of course, each world can be handled differently, as you've stated. 

---
### The location bar changing:

Yeah... the color changing here and there would be a nice touch.

---
DIMENSIONS

I like it.

Ever read any Robert Asprin *Myth Adventures* books?

Anyone who travels between dimensions is technically a 'demon' (a dimension traveller/hopper). They are commonly thought of as monsters simply because they look different, seeming how they're from a different dimension and all...

They have a device called a D-HOPPER in those stories. One of the main characters has magik joke-powder sprinkled him at the beginning of book one. The jokester is killed before he can counter-act the powder's effect, which is rendering said main character, Aahz (no relation) powerless. He then takes the dead magician's apprentice under his 'wing', and the fun begins! It's light, pun-filled reading. The first four books are right up there next to Douglas Adams on my bookshelf. (Of course, that's also due to the author's last name in alphabetical order arrangement I guess... Ah! Digressions!)

I only mention all this because something like a D-Hopper (a Dimension Hopper), which is faulty in the beginning, one of the main quests could involve fixing little bits of it after having collected the needed items or knowledge/experience by completing the side-missions in the different dimensions.

I also dig the Spell Reader idea, which scans in spells and takes the place of the outdated spell book.

The Spell Reader also has a digital readout of the local time (maybe other times too?). The time is off sometimes, goes backwards others, and sometimes doesn't work at all. (BUT, even a broken clock reads the right time twice a day! Puzzle in there!)

---
Brainstorming here, sorry...

**Comment by rheadkid** [comment]
```
if ((player.parent = RH_certain_room) and (player.RH_aware_of_d_travel)) {
  ppa_bak = player.parent.alias
  player.parent.alias = " + player.parent.alias + " in the dimension: " + player.parent.alias.dimension + "
}
```

I'm uncertain of that coding, but you can probably see what I was after:

Changing the room's display name once you've learned about dimension traveling.

---
We should also set up a website, or just a Gist, with details about different dimensions:
- which ones have magic force-lines to tap into
- which ones are peaceful and which ones aren't
- which ones have nice pubs
- insert more things here
- possibly someone could draw up nice maps? with different whatchacallits? Textures! That's it! Some can be scrolls, some like city maps, some like online maps...

---
We should also have an online game guide of some sort.

**Comment by ThePix** [comment]
> We should also set up a website, or just a Gist, with details about different dimensions:

Like an in-universe gazatteer? That would be cool.

**Comment by hegemonkhan** [comment]
or could code in a 'pedia' system into the game, to do this same thing (player can look up info about the game).

my use of 'pedia' refers to the Civilization games, which has a (GUI/UI) system that let's you click on various topics to view information about it.

here's an example of it (as a webpage/online), but this is a built-into the game as a GUI/UI that you can click on to go to different game topics/info:

ht.tps://www.civfanatics.com/civ4/civilopedia/

we can do the same in quest, albiet minus the fancy GUI/UI unless Pixie or whoever knows JS/CSS/HTML/etc really well (then we could create the same quality GUI/UI as the civilization games, muwahaha, we don't ahve to be professional game makers to do the same thing! we can do so with quest, as it was made really well, and we know JS/CSS/HTML/etc)

**Comment by rheadkid** [comment]
I guess this is where to put this:

We discussed turning off all automatic descriptions somewhere...

Would this stop it from printing, "There is a {random object player dropped here that doesn't belong here} here.'?

Because THAT would SUCK!

**Comment by rheadkid** [comment]
closing this one out

we can help each other out if a problem emerges

**Comment by DarkLizerd** [comment]
If nothing else, the main hub has a library...
and in the library there is a pedestal with on book securely connected to the pedestal so that it cannot be removed...
(and you'll like this part...)
The front cover has, in big, bold, pink, friendly letters... DON'T PANIC...
This could be the guide book for all the realms, and what the player could find, but some of the information could be incorrect, and have the player keep running into a field researcher by the name of Ford Perfect, that is trying to correct the Guide.
