### ISSUE TITLE
Features (score, health, money, ...)

### ISSUE THREAD

**Issue by rheadkid** [rheadkid/Quest-Group_Project#18]
- Ask/tell
- Use
- Everything else listed under Features

I assume all of this will be activated in the main file?

Should we all activate it as well, or how does that work?

**Comment by DarkLizerd** [comment]
**Money**: If each world had it's own currency, then the player could not load up on gold coins in one world and buy everything in another. This should make it easer to control how much money the player can collect at a time. AND, there is no cross world currency conversion.
I think, if everything is activated in the main world, all the worlds should have access to this. Each programmer should have a "simple" main world, then all their world's rooms will be under a "room" of their own name. Then when sending in their world code, it would be JUST their main room which will contain all their rooms.

**Comment by XanMag** [comment]
Score and health, yes.  Not such a fan of money.  I think earning things in a TA should be based on puzzle solving, not killing 78 gnomes to earn the 50gp needed for a potion.  Just my opinion.

**Comment by rheadkid** [comment]
Going with Score and Health.

We can always update things.

<sub>Issue Cuh-Lohsed.</sub>

> "My parents used to take me places all the time when I was a kid.
>  ...but I always found my way back home!"
>  -R. Dangerfield
