### ISSUE TITLE
Interface

### ISSUE THREAD

**Issue by rheadkid** [rheadkid/Quest-Group_Project#19]
>Input by command line or hyperlinks or panes

I vote for command line only

**Comment by DarkLizerd** [comment]
Command line (guess the verb) would be the easiest NOT to give away details the player will need to read to catch... Just like "in the old days".

**Comment by rheadkid** [comment]
We can set up a trigger:

If there are N number of unresolved commands in a row:

>'You seem to need a little help... You can enter HELP or HINT at any time. (For a list of exits, enter EXITS.)'

---

We can also set up a GUIDE ME THROUGH command, where hints and tips will be displayed in the text input box. These hints and tips would be conditional, of course. And each author would have to contribute their own or make a default 'Screw you, figure it out yourself!' message.

Well.. the main file would probably need the default 'screw you' response for the command patterns. (This idea may be too complicated.)

**Comment by hegemonkhan** [comment]
dido - I'm concuring with you guys so far in also (I think are) prefering to do typed-in inputs (command input bar/box//line)

I just personally like doing typed-in input myself as well, as it's fast (especially if just typing in a number/key), and less typing (less chance of carpal tunnel syndrone / tendididis --- can't spell). Having to constantly move the mouse to click on something and constantly clicking, does get irritating and tiring.

-------------

we can still do other methods too (if we want to cater to a wider audience and don't mind the extra work it involves and/or of our aesthetics/design interests), and/or for certain things.

**Comment by XanMag** [comment]
command line, no links

**Comment by DarkLizerd** [comment]
We can set up a trigger:
If there are N number of unresolved commands in a row:

Close, but having the program "ask" you or suggests something kills the flow of the story...
How about having an NPC show up and making a comment before wondering off...
Like:
You have been having problem trying to figure out how to open the door...
and you have failed 3 time at "guess the verb"...
"You stand at the door unable to figure out how to get the door open. 
You are interrupted by an old homeless guy wandering by. He stop next to you and comments, 
'Most people prefer that you knock on their door instead of trying to bust in.' then wanders off."

Or maybe the homeless guy just shows up, knocks on the door, it opens and he enters, then closes it behind him, ignoring you the whole time...

Or, for a forest or fantasy setting, a pixie or fairy, shows up and provides a hint, maybe with the requirement of solving a quest for her later.

**Comment by rheadkid** [comment]
>I just personally like doing typed-in input myself as well, as it's fast (especially if just typing in a number/key), and less typing (less chance of carpal tunnel syndrone / tendididis --- can't spell). Having to constantly move the mouse to click on something and constantly clicking, does get irritating and tiring.

I've been porting that game to Quest, making it where you can click to do EVERYTHING, testing and testing...

I had to sleep with my hand under the pillow to flatten it back out!

**Comment by hegemonkhan** [comment]
pressing a single key is the least amount of work upon the hand, as in text adventures, you got to do a lot of actions, so limiting the amount of hand work as much as possible is important.

while moving the mouse around, is a rest for your fingers (as you move from one button to another), however, people try to do this as quickly as possible, as this is a text adventure, and they have to do these actions to progress/play the game, so you learn how to do it as quickly as possible, which defeats the whole purpose of using the mouse and its delay/rest you get upon the fingers, as people are moving the mouse as quickly as they can from one button to another.

same is true for having to type a lot, long typed-in inputs, as this too can tire-out the hand/fingers and lead to tendinitis as well. Personally, I think the clicking of the mouse button is more strenous, as you're constantly gripping the mouse and pressing-with/moving/bending your fingers in one direction, which causes issues (when ever you move or stretch or lift weights or do whatever, you need to balance it in both directions, as you don't want to wear-out or make the muscles on one side be strong/over-worked and the other side's muscles to be weak/under-worked, as this different forces of muscle strength tear at your body and cause lots of bad issues/pain/injury.

**Comment by rheadkid** [comment]
ShowMenu prints hyperlinks even with hyperlinks off.

I'm sure there's an easy hack, but **I'm** not inclined to dick around with the default Functions on this one!

**Comment by rheadkid** [comment]
Listed the command line decision elsewhere

Closed
