### ISSUE TITLE
The working title?

### ISSUE THREAD

**Issue by rheadkid** [rheadkid/Quest-Group_Project#2]
What are we going to call it?

Also, who will be credited as the author?

We could go with something along the lines of David Agnew, which is what they used when the Doctor Who crew wrote the story. (Douglas Agnew, maybe? Or just THE QUEST FORUM?)

**Comment by DarkLizerd** [comment]
Name: we may need a theme first, then find a matching name.
Author: Me of course... 😄 (Or we could go with "The Quest Crew", then in the opening, list the authors. And maybe their part... Music, sound effects, pictures, videos, which worlds...)

**Comment by ThePix** [comment]
"Dimensions of Infinity" by David Agnew

We should get better names once the genre and hub are established.

**Comment by rheadkid** [comment]
I'd buy that for a dollar!

<sub>Robocop reference</sub>
