### ISSUE TITLE
Attributes (from The Pixie's Issue comment)

### ISSUE THREAD

**Issue by rheadkid** [rheadkid/Quest-Group_Project#20]
Attributes of the player object must be listed below. Names should be lowercase with no spaces, and succint but meaningful. They should be recorded in this document, with the type and any notes, which should include a note from any author intending to change it, and any restriction (eg health can be from 0 to 100).

### Player attrributes

|Attribute|Type|Notes
|-----------|-------------|-----------|
|alias|String|Set during character creation
isfemale|Boolean|True indicates female
|             |         |Set during character creation
|race|String|   Therace name in lower case, eg "human"
|            |         | Set during character creation

**Comment by hegemonkhan** [comment]
I'd have the 'isfemale' as being a String Attribute and renamed as 'sex', so that we have 3 sexes: male, female, and asexual (non-sexual) (robots/machines/etc which I think will probably be in the game... but maybe not, lol):

```
if (player.sex = "male") {
} else if (player.sex = "female") {
} else { // if asexual
}
```

**Comment by hegemonkhan** [comment]
if we're working with items, then we'd want to use:

weight/volume / quantity (custom)

type_of_object // (just an example name for it) // as a String Attribute
or
'WHATEVER_NAMES' // as Inherited Attributes (Object Types / Types)

maybe a storage system or whatever method for handling items (and/or equipment if we go there too)

**Comment by rheadkid** [comment]
So... Just to be clear:

I don't really know if there's already attributes I could be using for this but...

I made a simple example. There's one object you can take.

I set up a script on DROP HOE to remember what exact room the hoe was dropped in (I hope):

```
<attr name="_initialise_" type="script">
        if (HasAttribute(RH_hoe, "RH_left_in_room")) {
          StartMeElsewhere (this, "hoe.RH_left_in_room")
        }
      </attr>
      <ondrop type="script">
        RH_hoe.RH_left_in_room = RH_hoe.parent
        msg ("Dropped in " + RH_hoe.RH_left_in_room + ".")
      </ondrop>
```


To print a WELCOME or WELCOME BACK message upon entering my gateway via TRAVEL command, I have this (It will only print WELCOME BACK the first time you travel into the room the second time, I want it to print it every time the player enters the room via TRAVEL after visiting the first time. I just need to lose or add a flag, I'm sure. And that will not be the message. I'm putting bullshit text as filler until I have the mechanisms turning correctly.):

```
<enter type="script"><![CDATA[
      if (not GetBoolean(player, "RH_gateway_visited")) {
        msg ("<br/>Welcome, Adventurer!")
        SetObjectFlagOn (player, "RH_gateway_visited")
      }
      else if (not player.RH_came_from = RH_First_test_room) {
        msg ("<br/>Welcome back, Adventurer!")
        // SetObjectFlagOn (player, "RH_welcomed_back")
      }
    ]]></enter>
    <beforeenter type="script">
    </beforeenter>
    <exit alias="north" to="RH_First_test_room">
      <inherit name="northdirection" />
      <runscript />
      <script type="script">
        player.RH_came_from = player.parent
        MoveObject (player, RH_First_test_room)
      </script>
    </exit>
```

**Comment by rheadkid** [comment]
added wiki pages for good stuff

closed.
