### ISSUE TITLE
Start scripts

### ISSUE THREAD

**Issue by rheadkid** [rheadkid/Quest-Group_Project#21]
Should we use them?

**Comment by hegemonkhan** [comment]
The 'start' Script is nicely already built-in for us, and having an introduction for the game would probably be useful (if we're doing rpg stuff, we can do the character creation at the beginning too using the 'start' Script, or it can be done later on in the game too, character creation doesn't have to be done right away, which can make the game a bit more interesting, having a little tutorial/intro game before the actual game begins and doing character creation, or not, as the character creation could be delayed even further into the game as well)

**Comment by rheadkid** [comment]
To elaborate (sorry): should we fool around with the start scripts in our submissions? Or set our start scripts on our gateway rooms? 

I'm asking to make certain I'm putting this in the correct place once everything is combined:

```
if (Combined()) {
  msg ("This is the full version!")
}
else {
  msg ("<br/>("This is not the full version!)<br/>")
}
```

(I was playing my demo game and making notes/Issues, and never came back and added the specifics. Woops, sorry again.)

**Comment by ThePix** [comment]
Use the \_initialisation\_ script on the gateway object as the start script for your zone. It already has one line, which must not be changed, but you can add other stuff.

**Comment by rheadkid** [comment]
added a wiki page for this one

closed
