### ISSUE TITLE
Need a hint to enter TRAVEL in the hub's room description

### ISSUE THREAD

**Issue by rheadkid** [rheadkid/Quest-Group_Project#22]
Also, I just added that to the room description of the hub.

Will that break something?

**Comment by ThePix** [comment]
The command can be changed to whatever is appropiate.

The hub room description should all go in HubDescription in the library so it can be updated later. It does not matter yet, but when people are working on their games, the template becomes set in stone, but the library can get updated.

**Comment by rheadkid** [comment]
added in library, under hub enter room script

closed
