### ISSUE TITLE
To add an item to another creator's zone (or an NPC or, if using ConvLib, a conversation topic)

### ISSUE THREAD

**Issue by rheadkid** [rheadkid/Quest-Group_Project#23]
To add an item to another creator's zone (or an NPC or, if using ConvLib, a conversation topic), put the object in a room your game (not in the hub, it will get deleted, but you might want to have a room dedicated to this purpose). Go to its "Features" tab, and tick "Run an initialisation script". Go to the "Initialisation script", tab and paste in this script.

StartMeElsewhere(this, "px_academy_great_hall")

---
Do we add an ObjectList to the player attributes for all objects that were handled, then nest this in an IF...IS HANDLED, THEN... ?

If you just paste this in, the object appears in the room no matter what. I had an NPC holding mine at game start, but it was in the specified room I entered into this code at the beginning after doing this by itself.

Also, if I read it correctly, if you put a BS room name, the object will start off in the hub? That could prove useful... if it doesn't cause problems.

**Comment by DarkLizerd** [comment]
Sorry, I would not want NPCs in my area that I did not put there, but...
If you want one there, tell me, and we can work out where he would be, and how he will be treated.
Altho, I do like the idea of cross characters and items...
IE:
You enter the kitchen and a strange man is standing there. He notices you and says, 'Hi, I'm Bob and I need your help. I lost my hydro spanner around here somewhere and can't find it. If you find it, please bring it to me so I can fix the hyper drive on the Millennium Falcon.' He then pulls a device out of his pocket, point's it at the wall and a large black spot appears. He waves at you and steps through the spot and disappears, along with the spot. you check the wall, but it is still solid.
Now, somewhere in my world is a hydro spanner that I (or the player) needs to find... (What does a hydro spanner look like???!!!)
Which brings up an idea... I think we need a "Quest logbook" to keep track of tasks like this.

**Comment by hegemonkhan** [comment]
maybe it'd be better to have a "joint location" or a "hodge paug" (can't spell) location, which anyone can put whatever there, so it'll be a jumbled collection of all of our contributions, which could be kinda cool, and definately unique. As this way, we're not arguing with each other, messing with each other's areas and ideas.

**Comment by rheadkid** [comment]
Pixie has a variation of the joint location in the template and library.

```
<function name="StartMeElsewhere" parameters="obj, roomname">
    room = GetObject(roomname)
    if (room = null) {
      obj.parent = hub
    }
    else {
      obj.parent = room
    }
  </function>
```

You stick that into the object's `room initialisation` script.

Need to set up conditions on the it, though. (Just discovered this.) Otherwise, the object starts in the room you use in this rather than in the location you've set it up to start off in.

I figure the player.RH_carrying_objectname_on_exit attribute as a Boolean should cover that, though.

Here's Pixie's instructions-in-the-making:

https://github.com/rheadkid/Quest-Group_Project/wiki/Template-instructions-%5Bby-ThePix%5D

**Comment by ThePix** [comment]
> Sorry, I would not want NPCs in my area that I did not put there, but...

Absolutely this has to be done with the zone creator's permission. It has to fit their world; their style and their theme.

 Say there is a ket to one a door in your zone, and you want it to be found in another. The problem here is that you your game with justyour zone to work for testing purposes, and obviously you want the combined game with all zones to work too. You cannot put the key in the other zone yet - so it has to go in your zone, and get moved when the game starts. f this is the combined game, it goes to the proper location, other to the hub so you can test it works.

**Comment by ThePix** [comment]
The name of the initialisation script is \_initialisation\_, with underscores at start and end. Just realised that makes it display in italics.

**Comment by rheadkid** [comment]
We need to vote on each instance of 'shared objects/NPCs' is what it sounds like.

Adding a wiki page.

closed.
