### ISSUE TITLE
Ability to select EASY, NORMAL, HARD, EXPERIENCED, IMPOSSIBLE mode?

### ISSUE THREAD

**Issue by rheadkid** [rheadkid/Quest-Group_Project#25]
How hard would this be?

HP, STRENGTH, and everything else would be altered for each setting, maybe?

Is this a can of worms that should remain closed?

**Comment by hegemonkhan** [comment]
it depends on how robust we're going to make the game and/or its rpg aspects, though we should decide early, as it'd be a pain to go back into our game code and add/remove code for handling the aspects of the game that're effected by the 'difficulty state' chosen.

**Comment by rheadkid** [comment]
Maybe we should leave difficulty settings out.

**Comment by XanMag** [comment]
I'm anti-difficulty settings.  I say we make it difficult with the choice for help through a 'hints' option.

**Comment by rheadkid** [comment]
closed

can be reopened... but I'm thinking it's a can of worms
