### ISSUE TITLE
Just posted a sample

### ISSUE THREAD

**Issue by rheadkid** [rheadkid/Quest-Group_Project#28]
It's **VERY** rough.  

Probably won't even end up actually submitting one bit of it, but I want to make sure I'm doing everything right before I make anything much bigger.

NOTE: UPDATE: This link does not go to the latest update. I assumed it would stay current for some reason. I am putting little touches on this and updating the links within the hour.

[https://raw.githubusercontent.com/rheadkid/Quest-Group_Project/master/RH_examples_VERY_ROUGH_DRAFT/group_project.aslx](https://raw.githubusercontent.com/rheadkid/Quest-Group_Project/master/RH_examples_VERY_ROUGH_DRAFT/group_project.aslx)

[https://raw.githubusercontent.com/rheadkid/Quest-Group_Project/master/RH_examples_VERY_ROUGH_DRAFT/group_project_library.aslx](https://raw.githubusercontent.com/rheadkid/Quest-Group_Project/master/RH_examples_VERY_ROUGH_DRAFT/group_project_library.aslx)

UPDATED LINKS

**Comment by hegemonkhan** [comment]
Script Dictionaries are actually really useful, as Pixie/Jay has a cool trick that by using two Script Dictionaries, you can have parameters+values for the one Script Dictionary. In quick, generally it works (is set up) like this: by having one Script Dictionary use another Script Dictionary, that other Script Dictionary's keys and values, will be parameters and their values, for the one/main script dictionary. but, I'll let Pixie explain in more detail how it's done though, as he can better than I.

**Comment by rheadkid** [comment]
This issue is taking up space.

Closed.

**Comment by DarkLizerd** [comment]
OK, first problem...
Travel without a location generates an error.
You have no locations listed.
Travel without a location should give a list of places to go...
IE:
(after saying travel)
"A spinning sparkling orb-diamond-spikey 'thing' floats past you saying some things, a list perhaps...
But 'Dirt Farm' is the only thing you can make out."

**Comment by rheadkid** [comment]
>Travel without a location generates an error.

Hmm... mine is backwards. Travel by itself pulls up a menu of choices (1 choice at the moment), and TRAVEL #text# throws an error.

**Comment by rheadkid** [comment]
> (after saying travel)
> "A spinning sparkling orb-diamond-spikey 'thing' floats past you saying some things, a list perhaps...
> But 'Dirt Farm' is the only thing you can make out."

Different on my end again.

Shows this:

> Welcome to...
> Group project!
> A hub
> So this is the hub...
> You can enter TRAVEL to choose a destination.
> 
> > travel
> You travel in some unspecified manner...
> 
> A Richard Headkid's Dimension (this name is a placeholder)
> You can go north.
> 
> (This is not the full version!)
> 
> This is the gateway from my dimension to the main hub.
> 
> Enter TRAVEL to go the hub or NORTH to enter my dimension.
> 
> Welcome, Adventurer!
> 
> > travel hub
> I don't understand your command.
> 
> > travel
> You travel in some unspecified manner...
> 
> A hub
> So this is the hub...
> You can enter TRAVEL to choose a destination.

**Comment by rheadkid** [comment]
See how this works out. I think those links pointed to the original version, not the revised file...

I'm pretty sure you need my version of the library in the folder with the aslx for all my stuff to work, too.

[https://raw.githubusercontent.com/rheadkid/Quest-Group_Project/master/RH_examples_VERY_ROUGH_DRAFT/group_project.aslx](https://raw.githubusercontent.com/rheadkid/Quest-Group_Project/master/RH_examples_VERY_ROUGH_DRAFT/group_project.aslx)

[https://raw.githubusercontent.com/rheadkid/Quest-Group_Project/master/RH_examples_VERY_ROUGH_DRAFT/group_project_library.aslx](https://raw.githubusercontent.com/rheadkid/Quest-Group_Project/master/RH_examples_VERY_ROUGH_DRAFT/group_project_library.aslx)

**Comment by rheadkid** [comment]
Ah, I found this bit:

```
<command name="TravelFromHub">
      <pattern>travel</pattern>
      <script>
        ShowMenu ("Travel to where?", hub.destinations, true) {
          msg (TravelToHub.travelmsg)
          player.parent = GetObject(result)
        }
      </script>
    </command>
```

along with this one:

```
 <object name="hub">
    <inherit name="editor_room" />
    <attr name="feature_startscript" type="boolean">false</attr>
    <description />
    <enter type="script">
      HubEnterScript
    </enter>
    <destinations type="objectlist"></destinations>
```

But that would add another dimension besides the hub to travel to from my gateway...

We don't want that (without all the dimensions set up), right?

**Comment by rheadkid** [comment]
@DarkLizerd 

Are you using the latest version of Quest?

 5.7?

**Comment by hegemonkhan** [comment]
there's some options here:

1. have a check for 'ListCount'

(an Objectlist Attribute might require an item, not sure if it can have no items like a Stringlist Attribute can be empty/no-items)

```
if (ListCount (LIST) = 0) {
  msg ("There's currently no dimensions available to travel to at the moment")
} else {
  if (player.parent = NAME_OF_SELECTED_DESTINATION) {
    msg ("You're already at this dimension, silly.")
  } else {
    player.parent = NAME_OF_SELECTED_DESTINATION
  }
}
```

2. You can always use/have a default item that acts as 'null / no item', for example, having a 'cancel' string/object item, and use that for killing two birds with one stone: your lists will always have an item and you can use it for scripting out of the menu (aka: not doing anything), instead of using the built-in Parameter for canceling out of the menu.

for example, with equipment, I like having an 'unarmed' (which works for both weapon and armor) string/object for an item, which acts as a 'no equipment', while still being an item so that the list isn't ever empty.

3. we may be able to check for 'null' instead of doing the ListCount, but not sure.

4. there's probably many more designs that I can't think of at the moment... and Pixie can provide much better designs too.

**Comment by rheadkid** [comment]
I was adding to the template, not the library...

closed

**Comment by DarkLizerd** [comment]
Instead of using a "travel" command...
Why not just set-up the hub as a world in itself?
Then, just like regular "doors" or exits, that is how you enter each world.
Then there is no disconnect between the main hub and the connected worlds...

**Comment by rheadkid** [comment]
I _think_ that's Pixie's grand, master plan, but I'm not sure...

I sort of wanted the phone-booth in the beginning, before it was mentioned at all.

Then it was discussed, and we went a different route (which is fine, the thing we went with is much better).

Actually, I think we went a different route... I'm not being unpleasant here at all, I promise, but I missed it if we declared what is going on in the hub. I know that when we enter a gateway, we enter a new player object, but I don't have any idea how we 'leap', nor is it truly significant today, but still: I am curious... 

How does the player learn about the back story?

I'd like it if this is where you're dropped into the story:

> Somehow you have found a crack between the dimensions, and now you have a chance to go back to key events, and make sure they work out right for mankind this time around

.

We could still open with DEATH BY COMPUTER, landing us in PURGATORY. Then, we are sent back or escape through into the crack between the dimensions and wind up with the ability to 'leap'...

**Comment by rheadkid** [comment]
In retrospect, the doors would pose the following problem (unless we created exits in the hub on the fly):

The room description would have to be changed each time a dimension is submitted, unless we leave the exit listing feature on. I still don't know if that would pose a problem.

With TRAVEL, it's all packaged up neatly, and the room description matters not.

Thoughts?

**Comment by DarkLizerd** [comment]
I'm using Quest 5.7.1
Both of your files are in the same folder

> travel
Travel to where?
Error running script: Unable to cast object of type 'TextAdventures.Quest.Element' to type 'System.String'.

**Comment by DarkLizerd** [comment]
Whoever is in control of the hub would be told, when a world is updated, what exit to add to the new world.
My job requires about 6 hours of driving, I have already dreamed up the back story, based on the Hoard taking over all of time and space, (OK, maybe not space, but conquering the world through all of time.) How the player is introduced to it, and how it is decided what time windows he could enter to correct the time line. and what he would do to stop the Hoard at every time zone. AND, roughly how and when the game ends, win or loose. (maybe the game could be lost...)
I just need to write down what I dreamed up.

**Comment by rheadkid** [comment]
DarkLizerd,

Hrmm...

It threw an error similar to that when I copied the files into a new folder and ran Quest from that folder.

I eventually figured out to add the library from within the editor, but I bet that isn't the case with yours, AND I have a better test.


(NOTE: One of my PCs still has 5.6, and this will not load at all in it. Even the unaltered files straight from The Pixie. Just in case anyone has problems with that later.)

- Copy your game folder into a yourgamefolder-test folder.
    - this way, your game will be safe!

- Download this link and drop it in the newly created folder: https://raw.githubusercontent.com/rheadkid/Quest-Group_Project/master/rhLib.aslx

NOTE: This is a link to the RAW file. Watch out when right-clicking files to download from here! I kept having problems until I opened the .aslx I was dealing with to find it was in HTML format! I had right clicked to SAVE FILE AS...

- Once you have your copies of the template and library in that folder with rhLib.aslx, open the template up with Quest, add my library, and it should work.

I'm about to test it on a PC that's never had any of these files in it just to make sure, as well.

Let me know what you find, and you can send me what you have for me to test if it loads correctly, if you'd like.

**Comment by DarkLizerd** [comment]
When I start quest, by clicking on the group_project.aslx, group_project_library.aslx is the last thing loaded.
To me, it looks like Quest is loading your library.

**Comment by DarkLizerd** [comment]
Even with rhLib.aslx, loaded, and verified that it is there, I still get the same error...
That is why I'm pushing the hub to be a "world" itself, and just manually updating the exit links.
(K.I.S.S)

**Comment by rheadkid** [comment]
I just made a brand new folder called 'dof'.

Went to Pixie's page. Downloaded the current template and library by right-clicking RAW once on the file's main page.

I download the rhLib.aslx file from my repo.

So, I have a brand new folder with 3 freshly downloaded files.

I start it up. Add rhLib. Good to go! Have access to 1.RH_gateway and 2.gateway.

NOTE: If you don't load rhLib, it just doesn't show up as an option. It throws no error.

Here's my Quest specs, too:

Build 5.7.6404.27031


---
Have you opened rhLib with a text editor to see if it starts with the line ```<library>```? The different ways of downloading it messed my file all up. Right-clicking on Raw to Save As seems to be okay, though.

(If I'm repetitive, it's because I've gone slightly cuckoo. Too wired up on information and imagination to sleep! 40 is too old for that shit!)

---

> That is why I'm pushing the hub to be a "world" itself, and just manually updating the exit links.

Appears to not be a problem...
(Pixie updated the wiki on his repo.)

https://github.com/ThePix/quest/wiki/Group-Project

>Step 4: Update The Library

The library can be updated at the same time as people create their dimensions. There are broadly three reasons to update:

Add general commands and functions

Add other libraries (libraries can be invoked from other libraries and this is the best way to ensure everyone is using the same ones.

Change the hub

Functions in the library determine the hub room description and the player description, so these can be updated here as ideas develop, rather than in the template. The travel command can also be modified, so you could change the command pattern to include CATCH BUSES or CAST GATEWAY or whatever. The text displayed while traveling is an attribute of the command.

Once a dimension is completed, a copy should be sent to the project lead.

**Comment by DarkLizerd** [comment]
So... with everyone summiting their worlds as libraries, the hub is able to find each one with out code changes???
OK, so now, all I need to do is learn how to make my .aslx into a library...
I think, with a few sample worlds created and uploaded, we can see how this will all mesh together.

**Comment by rheadkid** [comment]
@DarkLizerd 

All you really do is copy all the code you add, including the gateway that you change, and paste it in between

```
<library>
  //ALL YOUR ADDED CODE GOES HERE
</library>
```

NOTE: There was something wrong in one of the files (template or library) In my repo somehow.



THIS HAS BEEN FIXED.

Download/Clone my repo again and check it out, please.

BACK YOUR CURRENT FILES UP IN A BACKUP FOLDER BEFORE YOU READ ON! YOU DON'T WANT TO LOSE ALL OF YOUR WORK!
---

IF YOU FORKED FROM MY REPO BEFORE I TYPED THIS, YOUR group_project.aslx and/or group_project_library.aslx PROBABLY NEEDS TO BE REPLACED BY THE CURRENT ONE.

BACK YOUR CURRENT FILES UP IN A BACKUP FOLDER! YOU DON'T WANT TO LOSE ALL OF YOUR WORK!
