### ISSUE TITLE
Wiki Pages / Articles

### ISSUE THREAD

**Issue by rheadkid** [rheadkid/Quest-Group_Project#29]
Everyone feel free to add wiki pages.

I'm pretty sure you can.

If you try and you can't, let me know, please.

**Comment by hegemonkhan** [comment]
probably one of the greatest resources is Kael n co, mod for civ4:

Fall From Heaven 2:

ht.tps://forums.civfanatics.com/threads/mod-fall-from-heaven-ii.171398/
ht.tps://forums.civfanatics.com/forums/civ4-fall-from-heaven.190/
ht.tp://kael.civfanatics.net
ht.tps://forums.civfanatics.com/threads/ffh-2-manual.265888/ (if you don't mind, download the FFH2 manual, and you can see much of this mods content, including on magic, there's a lot of really good content/ideas, as the makers of this mod, are long time pen and paper D&D, and have a really rich game design in FFH2)

**Comment by rheadkid** [comment]
unimportant at the present time

closed
