### ISSUE TITLE
The SHOWME command

### ISSUE THREAD

**Issue by rheadkid** [rheadkid/Quest-Group_Project#30]
I added ```SHOWME``` as a command pattern in the library example I posted.

It just gets all chlid items for the room. Strictly for testing purposes. (Inform includes it when releasing for testing. I need to make the off-shoot of it, SHOWME #object#, which would just be ```msg (object.parent)```.

**Comment by rheadkid** [comment]
I've got too many irrelevant issues open.

**Comment by ThePix** [comment]
SHOWME is useful, SHOWME #object# not so much. You can click on the debugger button while playing to see a list of object, and click on an object to see all its attributes (note that they do not update automatically).

**Comment by rheadkid** [comment]
It took a minute to click off of whatever I was attempting to debug then click back onto it.

After closing the debugger and opening it again didn't work, I was stumped. Accidentally found out how to work it fairly quickly though.

I did totally forget about the debugger though. (Slaps forehead.)

---
Closing this one out.
