### ISSUE TITLE
Adding Libraries

### ISSUE THREAD

**Issue by rheadkid** [rheadkid/Quest-Group_Project#32]
How will adding libraries work across the board?

If I include a library, like the Conversations library, will that cause problems if the main file is calling for the same library?

OR:

Will we just decide what libraries will be included from the jump, and make sure to have the appropriate files in our respective directories?

**Comment by ThePix** [comment]
You can add libraries to libraries, so the group project library can include libraries. If libraries get added later, the group project library can be updated to include the new library.

**Comment by rheadkid** [comment]
made wiki page

(now there will be 100 wiki pages, but bah! Easily delete-able! Plus, I found the button to set a custom side-pane up, so it isn't so cluttered. Plus, I provide what links we deem most important. (There's a drop down with links to all the pages there, too. Ha-ha!)

closed
