### ISSUE TITLE
An old thread on the forum with some good insights

### ISSUE THREAD

**Issue by rheadkid** [rheadkid/Quest-Group_Project#33]
https://textadventures.co.uk/forum/quest/topic/3524/why-is-quest-unpopular

(You'll have to ignore the argument that erupts, but some very good points are made in this thread. (HK was there....))

**Comment by ThePix** [comment]
So are we going to implement crates or not?

**Comment by hegemonkhan** [comment]
this forum/board of quest has the threads/posts on game design:

http://textadventures.co.uk/forum/design (lots of pages/threads/posts)

I also wrote this post too:

http://textadventures.co.uk/forum/design/topic/3877/make-your-game-worth-playing

(basically just describing a RPG, but that's why lots of people like them)

and here's just some ideas that I was trying to consolidate at one location as a resources for anyone to use:

http://textadventures.co.uk/forum/design/topic/3876/rpg-elements-game-mechanics-and-game-design

**Comment by rheadkid** [comment]
Heck yeah!!!

All different sizes and weights, too! 

In fact, we're gonna need to set up an elaborate attributes system for crates! Complete with string dictionaries and ALL the bells and whistles?

We can't let that [expletive deleted] dude down!

---
I vote we call the game Crate Quest, too.

---
How about The Questers' Quests?

---
Oh, I needed a good laugh!

I'm including DavidW in the special thanks!

**to DavidW:
So long, and thanks for all the crates!**

---
While there's an ```[expletive deleted]``` floating around here already...

Do we all watch R-rated movies?

My post would be much more concise if I weren't offending anyone by dropping the F - - -

If even one of use would rather not read such language, I have the utmost respect for that and shall continue to refrain from cursing like a sailor.

**Comment by rheadkid** [comment]
It looks like Pixie has an EXTENSIVE combat library set up.

Check out his wiki pages. Here's where it begins [CombatLib](https://github.com/ThePix/quest/wiki/CombatLib "Get comfortable! There are NUMEROUS pages concerning this library! (I have to read through it. I never have delved into it.").

It references spells and armor and pretty much everything else.

I bet we end up adding a few things to this and using it.

> This includes 20 spells, over 40 weapons and over 100 monsters.

**Comment by hegemonkhan** [comment]
I'm mature (and an adult), so language (and/or whatever doesn't bother me at all, excluding whatever extreme/illegal taboo stuff that might bother me) doesn't bother me, lol.

--------

that's something we need to decide upon as well:

the audience/clients of our game: do we make it for kids, teens, or adults?

**Comment by rheadkid** [comment]
Davidw will still complain/troll/negative-commentary...

Is he still a forum member?

(I'm going to post a question about CHEST ATTRIBUTES. Bwahahaha!)

**Comment by rheadkid** [comment]
Informative and entertaining, but ... closed.

**Comment by rheadkid** [comment]
Informative and entertaining, but ... closed.
