### ISSUE TITLE
if (not K_I_S_S = game.prototype_1)

### ISSUE THREAD

**Issue by rheadkid** [rheadkid/Quest-Group_Project#36]
if (not K_I_S_S = game.prototype_1) {
  msg ("Anyone think we may be blowing our wad?<br?>Maybe we should write ourselves a demo/intro game, using the defaults we decide on as a prototype? We could publish that as the 'teaser game', and plan sequels... (STAND ALONE SEQUELS!). Just thinking aloud...")
}

**Comment by XanMag** [comment]
"Maybe we should write ourselves a demo/intro game, using the defaults we decide on as a prototype?"

Yep.

**Comment by rheadkid** [comment]
Okay, and hell yeah!

I'm going to work up an example really fast, not many details, but the premise is easily expandable.

HUB:

The Public Domain
You can see Sherlock, Alice, Zorro, Robin Hood, Thor, and Dracula here.

\>x dracula
The count is holding a red herring sandwich. (He is currently counting the Sesame seeds.)

\>TRAVEL
Where would you like to travel to?
<a>1. Baker Street
2. Down the Rabbit Hole
3. Los Angeles
4. Sherwood Forest
5. Ásgarðr 
6. Transylvania</a>

**Comment by rheadkid** [comment]
See how this works out. I think those links pointed to the original version, not the revised file...

I'm pretty sure you need my version of the library in the folder with the aslx for all my stuff to work, too.

NOTE: In fact... It's probably wise to make a new folder to download each other's samples to when we're testing each other's stuff out. That way, their library file won't overwrite ours!

[https://raw.githubusercontent.com/rheadkid/Quest-Group_Project/master/RH_examples_VERY_ROUGH_DRAFT/group_project.aslx](https://raw.githubusercontent.com/rheadkid/Quest-Group_Project/master/RH_examples_VERY_ROUGH_DRAFT/group_project.aslx)

[https://raw.githubusercontent.com/rheadkid/Quest-Group_Project/master/RH_examples_VERY_ROUGH_DRAFT/group_project_library.aslx](https://raw.githubusercontent.com/rheadkid/Quest-Group_Project/master/RH_examples_VERY_ROUGH_DRAFT/group_project_library.aslx)

**Comment by rheadkid** [comment]
Will reopen later...
