### ISSUE TITLE
the Genre

### ISSUE THREAD

**Issue by rheadkid** [rheadkid/Quest-Group_Project#4]
We need votes on this one as soon as possible so we can get the stories cooking in our minds.

---
### Death while installing software

A shop-keeper, to whom you've unwittingly sold your soul while agreeing to all those terms and conditions.

...plus not bothering to actually read the license agreement when you install software.

You must deal with this character to obtain items and attributes, but he ends up being the devil in the details.

THIS CONCEPT IS SORT OF BASED ON A TRUE STORY.

Search terms and conditions immortal soul online if you're unfamiliar.

---
Not certain if this will be the lead-in to the Purgatory hub, or if this will be an underlying premise of the game.

Either way, the hub will lead to our separate 'zones', and we can most assuredly bend/cross-pollinate genres in the offshoots of the main hub.

---
Everyone voice your opinions!

This is a collaboration.

I'm not running this popsicle stand, we all are!

I'm just a small part of the grand scheme.

**Comment by DarkLizerd** [comment]
Other options:
Correct historic events. This would be a favorite of history fans... But, we need to get the history correct.
You are Thor, son of Zeus, your evil, trickster brother, Loci, has moved items between realms causing the realms to try and get their items back resulting in the realms closing to collide with each other, which would cause the universe to be destroyed. This one could have a time limit, based on movement turns. But it could be unwinnable if the time is too short. Could just use a pseudo timer giving the impression that time is running out.

**Comment by rheadkid** [comment]
Would Disney not shut us down for utilizing Thor and the gang?

Do they own Norse mythology now?

---
It seems like someone pointed out a good reason to avoid correct historic events, except as backstory. (I'm a history buff, so I like the idea, but it would reduce the effect the choices the player made would have on the game world, being that we stuck to the actual timeline.

BUT, someone else mentioned one of the Quests being going back to make sure Wild Bill got his gun and learned to shoot, or something to that effect.

That could work as a side-story that fit into the grand scheme of things.

(I can't remember who or when. I'll try to find it and copy it here.)

**Comment by DarkLizerd** [comment]
I gave Bill his gun...
Well, if not the major items, then maybe the "footnote" historic events... something that the player could pick up on. Like knowing that William Frederick Cody was "Buffalo Bill" ...
(but that may be a bit obscure of you are not an American "wild west" buff... )
I'm sure other countries have similar historic people that others will not even know about.

**Comment by DarkLizerd** [comment]
Maybe if we used The Avengers... But they should not have any control over the originals.

**Comment by rheadkid** [comment]
>Maybe if we used The Avengers... But they should not have any control over the originals.

I'm sorry, I forgot to add the 'ha-ha-ha' at the end of that question.

Hey! I read that three times and didn't notice til now, and it's a good puzzle:

Thor is depressed because he and his father, Zeus, having been getting along well...

We need Thor to be happy to F stuff up for us, so we can progress past it...

'But Thor,' we finally figure out to say, 'Odin is your father! Not Zeus!'

Classic NORSE-GREEK Mythology CROSSOVER Paradox SOLVED!

Now, we must go rescue Herakles from Odin in the next part...

(I'm typing in my sleep. Please ignore the last 2/3 of this...)

**Comment by hegemonkhan** [comment]
mythos (such as norse mythology) is public domain, a company can't trade mark 'cool' or a religion, lol... that would cause some serious mayhem... a company trying to get 'islam, christianity, judaism, buddhism (had to look up the spelling of this lol), hinduism'... that would be a "hornet's / african-killer-bees, nest" !!!!

though, we can't use any of disney's usages of the norse mythology of their thor/avengers movie series.

(joking: if anyone has norse mythology trademarked/copyrighted/patented... that would be JRPG companies, lol. Almost every staple of them is something from norse mythology, and some other mythos too to a lesser degree)

**Comment by XanMag** [comment]
I still love my idea (of course, as I am incredibly narcissistic... and handsome).  I copy-pasted from the TA forum the following:

> You start off some innocent tenderfoot (apprentice) with rudimentary skills... times "x" number of playable characters. Each character has a specifically unique "plebee-ness" and can be introduced at the start of the game. I see main characters as all different walks of life - a nerdy librarian, a body-building meathead, Napoleon's hairdresser, etc... Each character could be some insignificant underling to a famous character in history (if we want to go that route). Each character will have a very specific, but limited skill set. In the intro, each character can be approached by some "being" and proposed with the task of playing a role in saving future humanity. The task is to travel from their time in history and retrieve some historically significant artifact from some other time in history. The quirkiness might arise by the "being" accidentally sending the recruits on the wrong assignment. For example, sending Napoleon's hairdresser to the battlefields at Thermopylae to help Leonidas defeat Xerxes, send the nerdy librarian to the Mesozoic Era to retrieve the tooth of T-Rex, send the body-building meathead to the Elizabethan era to steal a Shakespearean work from the man himself.

If this idea is not on the table, I may eventually use it to drive my next game if ever I finish X3!

**Comment by ThePix** [comment]
The Night Emperor, his dreadlord lieutenants and legions of dark stalkers, void wraiths and blood angels have been battling mankind across time and space, and finally mankind has been beaten. Somehow you have found a crack between the dimensions, and now you have a chance to go back to key events, and make sure they work out right for mankind this time around.

Kind of like Quantum Leap and indeed DL's idea, but with magic.

**Comment by rheadkid** [comment]
Oh boy!!!

**Comment by rheadkid** [comment]
We need a ruling on this one, don't we think?

Along with the hub...

The two go hand in hand, after all.

It sounds like we're making a FANTASY / SCI-FI / HUMOUR / RPG / ADVENTURE game.

I'm fine with that, by the way. Especially considering the alternate dimensions...

What about the hub though?

I REALLY would like to have a blue phonebooth, but I like DEATH BY TERMS AND CONDITIONS a lot too...

HEY!

Our Purgatory can be computer hell!

What would you consider to be computer hell?

**Comment by XanMag** [comment]
Computer hell?  The online version of Quest.  Hahaha.

**Comment by rheadkid** [comment]
Ignore this.

Trying to figure out how we can easily 'vote'

- [ ] A) Science-Fiction
- [ ] B) Fantasy
- [ ] C) All of the above

- [ ] Science fiction

**Comment by DarkLizerd** [comment]
SciFi fantasy???
A SciFa???
I could go with some humor, but not so much the hack and slash horror.
And on that line, what rating will we aim for?
"G" may be hart to hit, but no need to go all out "R" with detailed sex acts...
"PG" or PG-13" should be good enough.
An F-bomb, were it applies should not be too much, But when the "edited" line looks like this...
"And there I F%$#@ing was minding my own F%$@#$ing business, when this F^%^$#@#ing bastard F%##$%#ing told me to F#@#%ing move my F$@!#^!ing ass so that he could F%$%!@#%ing ...." and so on... (Sadly, I've heard people talk this way, and more often than not, the call themselves "comedians"...
Is some one spoke this out loud, with someone beeping out the "bad" words, that would sound more like R2D2 than C3PO...

**Comment by XanMag** [comment]
Your grawlixes offend me.  😂

**Comment by rheadkid** [comment]
And the word of the day is:

**grawlix++
A string of typographical symbols, especially "@#$%&!", used (especially in comic strips) to represent an obscenity or swearword.

**Comment by rheadkid** [comment]
@DarkLizerd 

Bwahaha!

I **_knew_** `Sci-Fi/Fantasy` would get some conversation going!

There's definitely fiction, because, ya' know: we're making it up.

There's definitely science: otherwise, there would be nothing.

FANTASY: Doesn't including magic make it fantasy?

**Comment by XanMag** [comment]
Science = my profession.  If anyone needs helps with factualizing science while they write, please let me know.  Although I have the feeling most of you are pretty well versed in the sciences already.  Bunch of nerds... 🤓

**Comment by rheadkid** [comment]
> "PG" or PG-13" should be good enough.
> An F-bomb, were it applies should not be too much,

@DarkLizerd 
If it's a fucking Transformers 'movie', you can say 'fuck' twice and still get the PG-13...

**Comment by rheadkid** [comment]
@XanMag 

Can Carl Sagan be our shared NPC, if we decide to have one?

Like a real-life Doctor Who, travelling around in the Ship of the Imagination?

(And would that be appropriate? (Nothing but respect for Carl Sagan.))

---
Also,
Do you get an e-mail when I tag you? (If so, I'll reserve tagging for special occasions.)

**Comment by DarkLizerd** [comment]
Yes, got the e-mail... along with about 100 others of every posting done here...
I think reading the e-mails is the easiest way to see the latest posts...
Then respond here when needed.
Now that this is set up, I'm wondering... why?
Couldn't a new forum page be added that we could all post in, maybe private, enter my invite only, 
or, keep it open and maybe get feedback from curious visitors that want to add their $.02 worth, but don't think their programming skills are up to what we have set up, (little do they know how many newbie Quest programmers are included here!!! )

**Comment by DarkLizerd** [comment]
Maybe not a "shared" NPC, but each area SHOULD have an NPC that shows up from time to time to help the player through a hard part...
A pixie or fairy for DnD/ medieval era...
A floating sprite (like Bit, from Tron) for SciFi...
Or maybe a hologram from the future...
The image of Odin if you are in .... (that area)
or even a Smith, (The Matrix)
Altho, from the direction we seem be headed, "you inhabit someone from the ream you go to", you are some what like a Smith...

**Comment by rheadkid** [comment]
Damn and blast! Sorry about that. No more tagging unless it's important (which should be extremely rare, if ever).

---
I like the email method too, but I'm thinking of creating a dedicated email account.

---
Now I feel (appropriately) guilty, everyone!

I was posting shit on here left and right (as I'm sure you're MORE than aware), trying to get it all set up and organized...

I know I've been blowing you guys up!
Been at it constantly, for how many days? And I think I may have caught around three, 4-hour naps during it all, so...

Wow... Super sorry!

---

> Now that this is set up, I'm wondering... why?
> Couldn't a new forum page be added that we could all post in, maybe private, enter my invite only,
> or, keep it open and maybe get feedback from curious visitors that want to add their $.02 worth, but don't think their programming skills are up to what we have set up

I mentioned that up front, but never heard that it was do-able, and Pixie mentioned maybe using the Issues on here at the same time I was exploring that possibility, and here we are!

---
> (little do they know how many newbie Quest programmers are included here!!! )

I know I'm green!

And, to quote a great frog: "It ain't easy bein' green."

**Comment by DarkLizerd** [comment]
Not a problem...
But, if you use Outlook, and I would expect most other e-mail readers have the same option...
Just set up a rule so that all received e-mail from (every one here) just goes to junk...
Just kidding, goes to a folder called "Game Project", then all new e-mails will go there and not blow up your inbox...
(If we stay here, I'll be doing that!)

I new forum area will require a moderator to set up, us little "peon" users can't do that, but we could create new threads after that.

**Comment by rheadkid** [comment]
I can't find the thread where we were discussing this earlier.

RE: New area on textadventures forum

I brought that up the other day, but no one bit.

If a new forum area is possibly in the works, I'm gonna push pause on [Not a Forum](https://gist.github.com/rheadkid/a14c3c50e0bddabc003e370b64612c6c#discuss-random-things-here) and focus on other things to help us make this kick-ass game.

Plus, I could just drop links to the [Wiki](https://github.com/rheadkid/Quest-Group_Project/wiki) I've got (nearly) set up on the occasions that I add something new.

**Comment by ThePix** [comment]
Google groups might be an option.

**Comment by rheadkid** [comment]
I'm not whining, by the way!

I'm enjoying myself, and will probably keep learning and building onto this wiki regardless.

Having said that:

---

**I've not mastered GitHub, not one little bit.
Although I am learning 'bout wikis and gists!
To push or to pull?
Oh, don't I feel the fool!
And should I submit
Once I edit forked shit?**

**And do I fork my own?
What the hell's going on?
I know I could revert...
...but, if I mess stuff up, I'll still feel like a jerk!**

**See? My _-ameter_'s spent!
...or it's bent...
...but not '_pent-_'!
Is THAT a new Issue that I should submit???**

**I would ramble on,
and I could, all night long...
...but I gotta go work on the game.
So, so long!**

**Comment by rheadkid** [comment]
Marking it Sci-Fi and closing this one.
