### ISSUE TITLE
Artwork

### ISSUE THREAD

**Issue by rheadkid** [rheadkid/Quest-Group_Project#5]
I can almost draw stick figures.

I do know a guy who can draw fairly well though.

Any visual artists present?

**Comment by XanMag** [comment]
Again, pics eat up space.  Uploaded files have a size limit barring exceptions to this game.  If we do pictures though, it almost seems like the same person should artwork all of it.  I think it will be tough enough to make the written word sound similar enough not to be a smack in the face to whomever reads it... pictures on the other hand... those are incredibly difficult to make look analogous to those of other authors.

**Comment by rheadkid** [comment]
You make good points quite frequently, sir.

**Comment by rheadkid** [comment]
We'll need cover art, and some stuff for the site with the maps and such for the dimensions.

closing for now though
