### ISSUE TITLE
Do we want to close off dimensions?

### ISSUE THREAD

**Issue by rheadkid** [rheadkid/Quest-Group_Project#52]
Do we want the ability to close off dimensions, for whatever reason we may choose?

Here's the code to add a gateway:

``` xml

  <function name="AddToHubGateway" parameters="room">
    if (not room.alias = null) {
	name = room.alias
	}
	else {
	name = room.name + "_destination"
	}
    if (not GetObject(name) = null) error ("Something has gone wrong, and a destination is being added to the hub a second time.")
    create (name)
    obj = GetObject (name)
    obj.parent = destinations
    obj.look = room.dimensionderscription
    obj.alias = room.dimensionname
    obj.to = room
    obj.linkcolour = room.dimensioncolour
  </function>

```

---
## destroy

```destroy (string name)```

Destroys the specified object. Note that this takes the object’s name, not the object itself, as a parameter.

---
So, I could add this into the main library (unless someone can see that it would be bad to do this):
``` xml
  <function name="RemoveFromHubGateway" parameters="room">
    destroy (room)
  </function>

```

---
<sub>Grant the ability to remove a gateway from the list</sub>

**Comment by rheadkid** [comment]
Check if you want it:

- [ ] HK

- [ ] XM

- [ ] DL

- [ ] Pix

**Comment by XanMag** [comment]
I want to design my world so it could be re-examined and re-explored, if needed.  I could be easily convinced to close it off, however, if that is what the majority would want.  That is, assuming my "helpful NPC" could be accessed at the hub.

**Comment by rheadkid** [comment]
XM,

I was a tad vague.

I meant to we want the ability to close off our worlds.

---
Also, I like the helpful NPC idea, but I think the vote was 2 against 2 on that one...

**Comment by DarkLizerd** [comment]
How about a world attribute called IsOpen?
If it is false, then the world is not accessible at this time.
... second time visit to a world...
How about this:
XM_world_1... 
XM_world_1.IsOpen=true:
player visits, solves the quest, and leaves
This is set-up for just 1 visit, so, XM_world_1.IsOpen=false
later, an NPC shows up from XM_worls_1 with a problem, player must fix it...
 (a copy of XM_world_1 is XM_world_2 (but the link name (alias) is the same.
XM_world_2.IsOpen=true
player visits world_2 which is world_1 with the changes...
The IsOpen is in the world's code...
Nothing needs to be destroyed this way, and the programmer determines when a world is open.

**Comment by rheadkid** [comment]
Ah! Splendid!

That fits right into Pixie's current rhyme-scheme, too.

``` xml

 <function name="IsDimensionCompleted" parameters="gateway" type="boolean">
    return (gateway.completed)
  </function>
  
  <function name="AreAllDimensionsCompleted" type="boolean">
    flag = true
    foreach (obj, GetDirectChildren(destinations)) {
      if (not obj.to.completed) {
        flag = false
      }
    }
    return (flag)
  </function>
  
  <function name="DimensionComplete" parameters="gateway">
    gateway.completed = true
  </function>
```

---
**Check the box if you're for ```IsOpen```**

- [x] RH
- [ ] XM
- [ ] DL
- [ ] PIX
- [ ] HK
