### ISSUE TITLE
Music / Sound effects

### ISSUE THREAD

**Issue by rheadkid** [rheadkid/Quest-Group_Project#6]
We will include any audio?

We could have an opening crawl once the real story begins in the Purgatory hub if nothing else...

---
I dabble in guitar and can almost play some piano.

I have quite a few audio-editing programs at my disposal as well.

---
XanMag mentioned being able to help us out here in the forum thread, so there's one-and-a-half of us signed on in this department already! (Me being the half, of course.)

**Comment by XanMag** [comment]
Are we concerned about the limited file size on Quest?  Audio files will eat into that big time.  Or, will an exception be made for this project?

**Comment by rheadkid** [comment]
Probably not concerned about file size, but not certain.

If we're going full-blown, old-school parser, maybe audio would seem out of place...

Opening and closing theme songs would be sweet, either way.

NOTE: Deleted ```, IMO``` from post. Reason: redundancy. Every opinion I share is in my opinion.

**Comment by rheadkid** [comment]
We may well add in audio, but this won't effect the overall scheme of thing until later.

Will reopen.
