### ISSUE TITLE
the player

### ISSUE THREAD

**Issue by rheadkid** [rheadkid/Quest-Group_Project#7]
Who is the player?

Should we even know?

Are we the adventurer with no name? (And no mirror <del>to examine ourselves in</del>in which we can examine ourselves?)

I'm fairly certain the player will have some background in magic and some in combat, but beyond that: well, what do YOU think?

**Comment by DarkLizerd** [comment]
The less defined the player character is, the more the game player will relate. If it was "me" in the game, then the game is centered around "me". But, if I enter the game a Zelda, sword master, slayer of dragons, defender of the 3 kingdoms... then it is not "me" in the game. Then loosing is not so personal.

**Comment by rheadkid** [comment]
I concur.

I like being 'me' as well.

It's easier to write it that way too. You can be more vague, which allows room for the player's imagination to kick in.

**Comment by hegemonkhan** [comment]
dido, I concur as well.

for graphical rpgs, you can have a set main character, and thus can give him a unique/interesting personality and etc stuff (or the other obvious route for graphical rpgs, is full character creation with you choosing your character's appearance and etc stuff), but otherwise, usually it's better to have an ambigious character, so that you can be that character and thus be more immersed into the game world.

**Comment by rheadkid** [comment]
Once we get the last vote/word from @ThePix , we can settle this one.

(Yay!)

**Comment by XanMag** [comment]
The player is you.  Or is it me?  Either way, I agree with the above posters.

**Comment by rheadkid** [comment]
It seems that the popular consensus is:
- the player is just the player
- the player is a novice at magic

Not certain what we decided for the opening...

Death by computer?

Death by magic backfiring?

I like both...

How bout this:
THE COMPUTER IS POWERED BY MAGIC
(just like my Windows 98 machine! that sucker's still kicking! and it's fun to play TA on it!)

Electricity is technically magic in the real world, right?

We can pretty much control it.
We (pretty much) know how it will behave in numerous scenarios.
We know you can't kill it. (We've tried!)
We don't know where it came/comes from, but, when we make our own, bad things happen.

I'm categorizing that as 'magic'. The computer can plausibly run on magic, if we wish it to.

I'm closing this and opening a fresh one called: 

HOW DOES THE GAME START???

**Comment by rheadkid** [comment]
It seems that the popular consensus is:
- the player is just the player
- the player is a novice at magic
