### ISSUE TITLE
Proofreaders

### ISSUE THREAD

**Issue by rheadkid** [rheadkid/Quest-Group_Project#9]
I'll proofread everything I can, but I may ask for help if there's too much material.

This leads to a question The Pixie previously posed:

'Color' or 'Colour'?

(I think the rest of the world can adapt to American English easier than my fellow countrymen can adapt to what I like to refer to as English. (You know: English English. ACTUAL English.))

**Comment by DarkLizerd** [comment]
Could local variants to words be included?
I have seen some British TV, so...
Seeing a person taking a drag from a fag while I'm using a torch to light up the boot to find the keys to my flat so that I could take the lift and skip the treads... will not trip me up... (much)
So, we could use some cross cultural tweaking of items.
Now, just a thought, could the player identify where they are from so that the game could auto-tailor to their area... Language translations may be too much. but:
You go out to your {car.region.name}, to check the {car.region.trunk} for the key to your {home.region.name}.
So that in region="USA" it reads:
You go out to your car, to check the trunk for your key to your apartment.
Or, region="Britton":
You go out to your auto, to check the boot for your key to your flat.
Or we could just skip that work and go with American...

**Comment by rheadkid** [comment]
Is it "color" or "colour"?

```
msg ("Are you British, or do you misspell everything?")
get input {
   // script script script
}
```

(I misspell everything, by the way. So ha! The joke's on me!)

**Comment by hegemonkhan** [comment]
as for proof-reading:

I think this is something that everyone can and should do: "the more eyes, the better"

**Comment by XanMag** [comment]
The double 'L' thing is weird too.  Are we travelling or traveling?  =) 

I'll proofread the heck out of stuff.

**Comment by rheadkid** [comment]
I grew up with the real, British versions of the Dirk Gently novels and The Silmarillion, so I've always been cool with it either way. I actually have always used the double 'L' version: travelling. One 'L' looks strange t me, especially when I write it down. 

The -our is what slows my reading progress every time. That 'u' makes it ... not as clean is the best I can come up with... (I've only slept 4 hours in past 48, in my defense. (Too many thoughts concerning game design bouncing around in my head... gotta get it all written down! Ever seen Johnny Mnemonic? Well, I hope not, but, if you have, I'm totally like Ka-noo-noo Reeves right now! (Whoa! Excellent! (Cue guitar riff 1)))

---
And what about FANNY???

It means REAR-END over here in the US, right?

Well, from I've heard, it's slang for a vagina in the UK.

Imagine THAT miscommunication!

'HEY! WHAT DO YOU THINK YOU'RE DOING!?!?' the British lady exclaims.

'But... you said you wanted it in your fanny...' mumbles the confused American.

---
That made me think about Kate trying to get a pizza delivered to her in London in **THE LONG, DARK TEA-TIME OF THE SOUL**, which made me think of the wandering vending machines... 

You know: the wandering vending machines that Odin was using to traverse interdimensionally?

Sounds like something we could adapt into this game that would a good (and funny) reason for showing up randomly in our different dimensions.

It could also be a way to get object1 from dimension A to dimension B:
- If you haven't solved PUZZLE42, everything you put in the machine goes to a random room in a random universe
- If you HAVE solved PUZZLE42, not only are you now holding a towel, but you can also put everything you want to go to the main hub into the machine.

Too much? Not original enough?

(Can't... fight... the urge... to reference.... Douglas Adams!)

**Comment by DarkLizerd** [comment]
I think everyone will be proofreading each other's work as we playtest each other's works as well. (And I bet there will be quite a few "stealing" of ideas back and forth!)

**Comment by DarkLizerd** [comment]
The Douglas Adams reference brings something to mind...
Are we going for something totally serious, something funny, something with some witty humor thrown it?
Could the player keep running into a strange character that keeps asking him, 'Where's your towel?'

**Comment by rheadkid** [comment]
@DarkLizerd 

I reopened all the issues.

Here's one regarding the NPC who shows up in the different dimensions:
https://github.com/rheadkid/Quest-Group_Project/issues/23
